name:                siam
version:             0.1.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2023 barsanges

extra-source-files:
- README.md

synopsis:            An implementation of the board game "Siam"
description:         Please see the README

dependencies:
- base
- brick
- containers
- microlens-mtl
- microlens-th
- vty

library:
  source-dirs: src

executables:
  siam:
    source-dirs:     app
    main:            Main.hs
    dependencies:
    - siam

tests:
  siam-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - siam
    - hspec
